spring:
  profiles:
    active: "dev"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takenote
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      dd-auto: validate
    generate-ddl: true


---
spring:
  profiles: "stage"