spring:
  profiles:
    active: "dev"
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgress
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      dd-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        default_schema: takenote


---
spring:
  profiles: "stage"